muralifpb/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import url

from .views import (index, account, register, edit_password, edit_user, search,
add_category,
edit_category,
delete_category,
add_post,
edit_post,
delete_post,
add_portal,
edit_portal,
delete_portal,
)

urlpatterns = [#'muralifpb.views', #prefixo

	url(r'^$', index, name='index'),

	url(r'^register/$', register, name='register'),

	url(r'^add_category/$', add_category, name='add_category'),

	url(r'^edit_category/(?P<id>\d+)/$', edit_category, name='edit_category'),

	url(r'^delete_category/(?P<id>\d+)/$', delete_category, name='delete_category'),

	url(r'^add_post/$', add_post, name='add_post'),

	url(r'^edit_post/(?P<id>\d+)/$', edit_post, name='edit_post'),

	url(r'^delete_post/(?P<id>\d+)/$', delete_post, name='delete_post'),

	url(r'^add_portal/$', add_portal, name='add_portal'),

	url(r'^edit_portal/(?P<id>\d+)/$', edit_portal, name='edit_portal'),

	url(r'^edit_user/$', edit_user, name='edit_user'),

	url(r'^account/$', account, name='account'),

	url(r'^search/$', search, name='search'),

	url(r'^edit_password/$', edit_password, name='edit_password'),
]

website/urls.py
# -*- coding: UTF-8 -*-
"""website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
	https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
	1. Add an import:  from my_app import views
	2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
	1. Add an import:  from other_app.views import Home
	2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
	1. Add an import:  from blog import urls as blog_urls
	2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login
from django.contrib.auth.views import logout

urlpatterns = [
	url(r'^mural/', include('muralifpb.urls', namespace='mural')),

	url(r'^login/$', login, {'template_name' : 'login.html'}, name='login'),

	url(r'^exit/$', logout, {'template_name' : 'index.html'}, name='logout'),

	url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account.html
{% extends 'base.html' %}

{% block title %}IFPB account {{ request.user.username }} {% endblock %}

{% block content %}

	<div id="main" style="width: 1200; height: 900; overflow: auto;">
		{% if request.user.is_authenticated %}
			<h1>Publicados</h1>
			{% if posts %}
				<ul>
					{% for post in posts %}
						<li><a href="{% url 'delete_post' post.id %}">{{ post.id }}</a>
						<li>{{ post.category.name }}</li>
						<li>{{ post.title }}</li>
						<li>{{ post.text }}</li>
						<li>{{ post.created_on }}</li>
						<li>{{ post.updated_on }}</li>
						<li>{{ post.published }}</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>not list!</p>
			{% endif %}

			<hr>
			
			<h1>Não publicados</h1>
			{% if unposts %}
				<ul>
					{% for post in unposts %}
						<li><a href="{% url 'delete_post' post.id %}">{{ post.id }}</a>
						<li>{{ post.category.name }}</li>
						<li>{{ post.title }}</li>
						<li>{{ post.text }}</li>
						<li>{{ post.created_on }}</li>
						<li>{{ post.updated_on }}</li>
						<li>{{ post.published }}</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>not list!</p>
			{% endif %}

		{% else %}
			<h1 align="center"><b>unauthenticated user</b></h1>
		{% endif %}
	</div><!--main-->
	
{% endblock %}

templates/add_portal.html
{% extends 'base.html' %}

{% block title %}IFPB news - Adicionar Postais de Notíciais{% endblock %}

{% block content %}

	<div id="main" align="center">
		<h2>Portal</h2>

		<form action="." method="POST" >{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" />
		</form>

		<hr>

		<h3>Lista de Postais de Notíciais </h3>

		{% if portals %}
			{% for portal in portals %}
				<p>{{ portal.id }} {{ portal.name }} {{ portal.link }}</p>
			{% endfor %}
		{% else %}
			<p>not list!</p>
		{% endif %}
	</div>

{% endblock %}

templates/add_post.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}IFPB news - Adicionar Postagens {% endblock %}
{% block extrahead %}<link href="{% static 'muralifpb/css/css-for-errors-li.css' %}" rel="stylesheet" type="text/css" media="all">{% endblock %}

{% block content %}
	<div id="main" align="center">
		{% if success %}
			success
		{% else %}
			unsucess
		{% endif %}
		{% if request.user.is_authenticated %}
			<form action="." method="POST" enctype="multipart/form-data" >{% csrf_token %}
				<div class="block-login">
					<h2 class="title">Post</h2>
					{{ form.as_p }}
					<input class="button button-color" type="submit" name="Sign in" value="Sign in" >
				</div>
			</form>
		{% endif %}
	</div>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" media="all"/>
	<link rel="shortcut icon" href="{% static 'muralifpb/img/favicon.ico' %}" type="image/x-icon" />
	<title></title>
	<!-- Compiled and minified CSS -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css" media="all"/>
	<link rel="stylesheet" href="{% static 'muralifpb/css/my-style.css' %}"></link>
	<!-- Compiled and minified JavaScript -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
</head>
<body>
	<nav>
		<div class="nav-wrapper green z-depth-1 white-text text-darken-2">
			<a class="brand-logo center logo" href="{% url 'mural:index' %}"><img class="responsive-img" src="{% static 'muralifpb/img/logo-conexao-map.png' %}" /></a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				{% if request.user.is_authenticated %}
					{% if request.user.is_staff %}
						<li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ request.user.username }} Admin<i class="material-icons right">arrow_drop_down</i></a></li>
						<ul id="dropdown1" class="dropdown-content drop-mrc-1">
							<li><a href="{% url 'mural:edit_user' %}" >Perfil</a></li>
							{% if request.user.is_staff %}
								<li><a href="{% url 'mural:register' %}">Cadastrar</a></li>
							{% endif %}
							<li><a href="{% url 'mural:account' %}">account</a></li>
							<li><a href="{% url 'logout' %}">Exit</a></li>
						</ul>
					{% else %}
						<li>{{ request.user.username }} Estudante</li>
					{% endif %}
				{% else %}
					<li><b>IFPB news</b></li>
					<li><a href="{% url 'login' %}">Log in</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>
	{% block content %}{% endblock %}
	<footer class="page-footer green">
		<div class="container">
			<div class="row">
				<div class="col l12 m12 s12">
					<p class="center-align">Desenvolvido Jerônimo Gabriel</p>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>

templates/base1.html
{% load staticfiles %}
{% load mural_tags %}

<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>{% block title %}{% endblock %}</title>
		<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css" media="all">

		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>]

		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

		<!-- <link href="{% static 'muralifpb/css/my-style.css' %}" rel="stylesheet" type="text/css" media="all"> -->
		<link rel="shortcut icon" href="{% static 'muralifpb/img/favicon.ico' %}" type="image/x-icon" />
		{% block extrahead %}{% endblock %}
		{% block extrajs %}{% endblock %}
	</head>
	<body>
		<div id="header">
			<div id="box-header">
				<div id="logo-if">
					<a href="/"></a>
				</div><!--logo-if-->
				
				<div >
					{% if request.user.is_authenticated %}
						{% if request.user.is_staff %}
							{{ request.user.username }} Admin
						{% else %}
							{{ request.user.username }} Estudante
						{% endif %}
					{% else %}
						<b>IFPB news</b>
					{% endif %}
				</div><!--search-->

				<ul class="menu">
					{% if request.user.is_authenticated %}
						<li><a href="#"><img src="{% static 'muralifpb/img/ic_settings_black_24dp_2x.png' %}" alt="Opções" style=" display: inline; width: 35px; height: 35px;" /></a>
							<ul>
								<li><a href="{% url 'edit_user' %}" >Perfil</a></li>
								{% if request.user.is_staff %}
									<li><a href="{% url 'register' %}">Cadastrar</a></li>
									<li><a href="{% url 'search' %}">Search</a></li>
								{% endif %}
								<li><a href="{% url 'account' %}">account</a></li>
								<li><a href="{% url 'index' %}">Exit</a></li>
							</ul>
						</li>
					{% else %}
						<li><a href="{% url 'login' %}">Logar</a></li>
					{% endif %}
				</ul>

				
			</div><!--box-header-->
		</div><!--header-->
		
		{% block content %}

		{% endblock %}
	
		<div id="footer">
			<div id="credits" align="center">
				<p>Desenvolvido Jerônimo Gabriel</p>
			</div><!--credits-->
		</div><!--footer-->
	</body>
</html>

templates/edit_category.html
{% extends 'base.html' %}

{% block title %}IFPB Editar usuário {{ category.name }}{% endblock %}

{% block content %}

	<div id="main">
		<form action="." method="POST" >{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" />
		</form>
	</div>
	
{% endblock %}

templates/edit_password.html
{% extends 'login.html' %}
{% load staticfiles %}

{% block title %}IFPB edit password{% endblock %}
{% block extrahead %}<link href="{% static 'muralifpb/css/css-for-errors-li.css' %}" rel="stylesheet" type="text/css" media="all">{% endblock %}

{% block dashboard_content %}
	{% if success %}
		success
	{% else %}
		unsucess
	{% endif %}
	<div id="main" align="center">
		<form action="." method="POST" >{% csrf_token %}
			<div class="block-login">
				<h2 class="title">Change Password</h2>
				{{ form.as_p }}
				<input class="button button-color" type="submit" name="Sign in" value="Sign in" >
			</div>
		</form>
	</div>

{% endblock %}

templates/edit_post.html
{% extends 'login.html' %}

{% block title %}IFPB Editar post {{ post.title }} {{ post.author.user.username }}{% endblock %}

{% block dashboard_content %}

	<div id="main">
		<form action="." method="POST" >{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" />
		</form>
	</div>
	
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load mural_tags %}

{% block title %}IFPB news{% endblock %}

{% block content %}
	<div class="row">

		{% show_posts %}

		<div class="col s3 news white ">
			<h5 class="center-align">Notícias</h5>
			<blockquote class="" >
				This is an example quotation that uses the blockquote tag.
			</blockquote>
		</div>

		{% show_posts_reitoria %}
 		
	</div>
	<script type="text/javascript" src="{% static 'muralifpb/js/index.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}IFPB login{% endblock %}
{% block extrahead %}<link href="{% static 'muralifpb/css/css-for-errors-li.css' %}" rel="stylesheet" type="text/css" media="all">{% endblock %}

{% block content %}
<div class="section no-pad-bot">
	<div class="container">
		<div class="row">
			<form action="." method="POST" class="col center-align s12">{% csrf_token %}
				<div class="row">
					<h3 class="title">Login</h3>
					<div class="col s6 offset-s3 card">
						{{ form.non_field_errors }}
						<div class="row" style="padding: 15px;">
							<div class="input-field col s12 black-text">
								{{ form.username }}
								<label for="username">{{ form.username.label }}</label>
							</div>
						</div>
						<br >
						<div class="row" style="padding-right: 15px; padding-left: 15px;">
							<div class="input-field col s12 black-text">
								{{ form.password }}
								<label for="username">{{ form.password.label }}</label>
							</div>
						</div>
						<button style="margin: 15px;" class="waves-effect waves-light btn">login</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}IFPB news - register User{% endblock %}
{% block extrahead %}<link href="{% static 'muralifpb/css/css-for-errors-li.css' %}" rel="stylesheet" type="text/css" media="all">{% endblock %}

{% block content %}
	{% if success %}
		success
	{% elif form.errors %}
		{{''}}
	{% else %}
		unsucess
	{% endif %}
	<div id="main" align="center">
		{% if request.user.is_authenticated and request.user.is_staff %}
			<form action="." method="POST" >{% csrf_token %}
				<div class="block-login">
					<h2 class="title">Register User</h2>
					{{ form.as_p }}
					{{ user_form.as_p }}
					<input class="button button-color" type="submit" name="Save" value="Save" >
				</div>
			</form>
		{% else %}
			<h1 align="center"><b>you do not have permission</b></h1>
		{% endif %}
	</div>

{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}IFPB search {% endblock %}
{% block extrahead %}<link href="{% static 'muralifpb/css/css-for-errors-li.css' %}" rel="stylesheet" type="text/css" media="all">{% endblock %}

{% block content %}
	<style type="text/css">
		table {
		    border-collapse: collapse;
		    width: 100%;
		}

		th, td {
		    text-align: left;
		    padding: 8px;
		}

		tr:nth-child(even){
			background-color: #f2f2f2;
		}

		th {
		    background-color: #4CAF50;
		    color: white;
		}
	</style>
	
	<div id="main">
		<dir class="div">
			<h2 class="title">Lista de Users</h2>

			<table >
				<thead>
					<tr>
						<th>Matricula</th> 
						<th>Name</th>
						<th>Email</th>
					</tr>
				</thead>
				<tbody>
					{% if users %}
						{% for user in users %}
							<tr>
								<td><a href="">{{ user.matricula }}</a></td>
								<td>{{ user.username }}</td>
								<td>{{ user.email }}</td>
							</tr>
						{% endfor %}
					{% else %}
						<p>not list!</p>
					{% endif %}
				</tbody>
			</table>
		</dir>
	</div>
	
{% endblock %}

templates/show_news.html
<hr>
	{% if news %}
		{% for news in news %}
			{{ news.title|title }}
			{{ news.text|addslashes }}
			{{ news.published_date }}
			{{ news.link }}
		{% endfor %}
	{% else %}
		<p>not list!</p>
	{% endif %}

templates/show_posts_reitoria.html
{% load staticfiles %}

<h6 class="title-chat-restory right">Publicações</h6>

<div class="col s3 chat-rectory right white">
	<h5 class="center-align">Estudantes</h5>
	<a class="btn-floating btn-large waves-effect waves-light" href="#modal2">
		<i class="large material-icons">mode_edit</i>
	</a>
	<div>
		<!-- {% for post in posts %} -->
			<blockquote class="" >
				This is an example quotation that uses the blockquote tag.
			</blockquote>
		<!-- {% endfor %} -->
	</div>
</div>

<!-- Modal Structure -->
<div id="modal2" class="modal bottom-sheet col s6">
	<div class="row'">
		<div class="input-field col s12">
			<i class="material-icons prefix">mode_edit</i>
			<textarea id="icon_prefix2" class="materialize-textarea"></textarea>
			<label for="icon_prefix2">Message</label>
		</div>
	</div>
	<div class="modal-footer">
		<a class="btn-floating btn-large waves-effect waves-light right">
			<i class="material-icons right">send</i>
		</a>
	</div>
</div>

<script type="text/javascript">
 $(document).ready(function(){
	$('.modal').modal();
  });
</script>

<style type="text/css">
	p {
		font-weight: 900;
		line-height: 1.1;
	}
</style>

<!-- <dir id="left" class="floating-left" style="overflow: auto;">
	<h6>Direção</h6>
	<ul style="margin-top: 5px; ">
		{% for post in posts %}
			{% if post.author.is_reitoria %}
				<dir style="background: rgba(179,255,206,0.17); list-style-type: none; margin-left: 3px; margin-right: 3px; border-radius: 5px; border: 1px solid rgba(6, 72, 3, 0.28); margin-top: 3px; margin-bottom: 3px; ">
					{% if post.author.image %}
						<li style="font-weight: 900;">
							<img src="{ post.author.image.url }" style="margin-right: 0px; float: ;" />
							<dir style="margin-right: 0px; margin-top: 0px; " >
								<p>{{ post.author.username|capfirst }} {{ post.created_on }}</p>
							</dir>
						</li>
					{% else %}
						<li>
							<dir style="margin-top: 0px; display: block;">
								<img src="{% static 'muralifpb/img/ic_person_black_48dp_1x.png' %}" 
									style="margin-left: 5px; float: left; display: inline; margin-top: 0px; margin-bottom: 3px;" 
								/>
							</dir>
							<dir style="margin-right: 0px; display: block; margin-left: 10px; margin-top: 10px;" >
								{{ post.author.username|capfirst }} 
								<dir style="display: block; margin-top: 8px; margin-bottom: 5px; opacity: 0.50;">
									<p style="font-size: 10px;">{{ post.created_on }}</p>
								</dir>
							</dir>
						</li>
					{% endif %}
					<li style="margin-left: 155px; margin-bottom: 0px;">
						{{ post.title|title }}
					</li>
					<li style="margin-left: 15px; margin-top: 15px; color: #191970; ">
						<dir style="font-weight: 900; display: inline; ">
							{{ post.text|capfirst|addslashes|linebreaks }}
						</dir>
					</li>
					{% if post.image %}
						<li>
							<a href="{{ post.image.url }}">
								<img src="{{ post.image.url }}" 
									style="margin-left: 5px; margin-top: 3px;  max-width: 97%; max-height: 40%; width: auto; height: auto;" 
								/>
							</a>
						</li>
					{% endif %}
					<br>
				</dir>
			{% endif %}
		{% endfor %}
	</ul>
</dir> 